### ISSUE TITLE
Token compiles but does not work when deployed[Bug]

### ISSUE THREAD

**Issue by mikejsdev** [solidity-guru/safetoken#1]
This can be compiled on remix etherum successfully and deployed to the Bsc Testnet. However, when deployed and viewed on Bsc scan, you cannot see any details like the name or symbol of the token which implies something is wrong with it. When trying to add it to wallets, either meta mask or pancakeswap (testnet) it does not appear when entering the contract address indicating again that something is wrong with the token.

Am I doing something wrong? Has the deployment of this been tested by anyone?

Thanks

**Comment by mikejsdev** [comment]
Just to add more context, after deploying it is not possible to see any of the functions in the contract in remix:

![1](https://user-images.githubusercontent.com/26206730/129404171-1b9707e7-929e-486c-9e95-8fe3f3e26fa9.PNG)

and none of the token details are in Bsc Scan e.g. name or symbol. it is not possible to add this to a wallet or do anything with it. Despite compiling 
![2](https://user-images.githubusercontent.com/26206730/129404232-56212848-3f2f-48ef-939b-684587430b3f.PNG)
correctly it is broken.

**Comment by triplenick** [comment]
You're doing something wrong, maybe messing with the contract. Choose the [yourtokenname] contract in the drop-down menu when you deploy.

Also might resolve the bug: 
- use chrome browser
- use http version of the remix
- create new workspace and put safetoken.sol & safetoken-imports.sol to the "contracts" folder
- in the bottom of the code make sure it looks like this: contract [yourtokenname] is SafeToken
- and of course make sure you're deploying [yourtokenname] contract

I'm not a pro, so I can only make my guesses.

**Comment by mikejsdev** [comment]
@triplenick thank you so much!

It was totally my mistake, your bottom two bullet points fixed it for me!!

Thanks again

Mike

**Comment by mikejsdev** [comment]
Closing as there was no actual problem.

**Comment by 0f0crypto** [comment]
Yeah, you were deploying the incorrect contract (Address) :)
