### ISSUE TITLE
undefined error on pancakeswap when selling

### ISSUE THREAD

**Issue by mikejsdev** [solidity-guru/safetoken#2]
Removing this issue is it was a problem with slippage by user, not the code!

**Comment by mikejsdev** [comment]
I have been looking into this and it is clearly a problem with the _transfer function when it tries to add fees when the recipient is the _pair address (i.e. someone is selling the token, though not the contract owner). 

Adding _isV2Pair(recipient) to line 516 makes it not break but means that no sell fees are added.

Change from:

`if ( !takeFee ){ sumOfFees = 0; }`

To:

`if ( !takeFee || _isV2Pair(recipient) ){ sumOfFees = 0; }`

This is in the _transferTokens function. This change at least stops the contract breaking completely when a non contract owner tries to sell tokens, but it means that the _takeTransactionFees function is not called so I guess this is where the problem is?

I am testing by deploying from remix onto bsc testnet and using the testnet pancakeswap https://pancake.kiemtienonline360.com/#/swap to add liquidity and then buy/sell

I am unable to get the debugger working but if someone can debug this hopefully the problem will leap out. Any help would be much appreciated.

Thanks

**Comment by 0f0crypto** [comment]
This code has been fully tested and works out of box for *all* wallets (all wallets can buy and sell). If you get an error you've done something wrong (e.g. you didn't set high enough slippage)
